version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/tools/releases/dockerfiles"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
