apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-play
  labels:
    app: api-play
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-play
  template:
    metadata:
      labels:
        app: api-play
    spec:
      containers:
        - name: app
          image: ghcr.io/lahabana/api-play:main
          imagePullPolicy: Always
          args: [-config-file, /etc/config/config.yaml]
          volumeMounts:
            - name: config
              mountPath: /etc/config
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
      volumes:
        - name: config
          configMap:
            name: api-play
---
apiVersion: v1
kind: Service
metadata:
  name: api-play
spec:
  selector:
    app: api-play
  ports:
    - protocol: TCP
      appProtocol: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-play
  labels:
    app: api-play
data:
  config.yaml: |
    apis:
    # A simple call that adds random latency to each call
    - path: with_latency
      conf:
        latency:
          min_millis: 200
          max_millis: 400
        body: I have latency
